### ISSUE TITLE
"Error while enabling app"

### ISSUE THREAD

**Issue by wallyreport** [lebowski42/owncloudapp-dokuwiki#1]
I feel certain that I have followed all the instructions. But I am getting an "Error while enabling app" message when I try to enable the Dokuwiki app on ownCloud. 

I am using the most recent stable version of each. OwnCloud version 5.0.10. And Dokuwiki Release 2013-05-10a "Weatherwax." 

I am runing on a CentOS 6.4 x86_64 OS, with Apache 2.2.15.

**Comment by starboerg** [comment]
I fixed this error by renaming the Dokuwiki app folder to something simpler, not containing hyphens. Apparently OwnCloud cannot handle such 'special' chars in app folders ;-).

**Comment by wallyreport** [comment]
I have, pretty much, given up on owncloud. Owncloud is not ready for prime-time, IMO.

**Comment by afiore1961** [comment]
Thank you for the info. I shall try to folder-names solution
