### ISSUE TITLE
App does not appear in owncloud app manager

### ISSUE THREAD

**Issue by goulou** [lebowski42/owncloudapp-dokuwiki#2]
Hi, 

I downloaded the dokuwiki app from the owncloud app store, unzipped in my apps/ directory, but it does not appear in the app manager of owncloud.
I checked that other apps work, and I set up the permissions correctly.
I am using owncloud 5.0.11.

I'll be very happy if anyone has an idea on how to make the app work.

Thank you in advance!

Goulou

**Comment by lebowski42** [comment]
Hi,  

who is the name of folder. Maybee it's ist somethong like 'owncloudapp-dokuwiki-master'. Please rename it to 'dokuwiki'. Then it will work. Also look here: https://github.com/lebowski42/owncloudapp-dokuwiki/issues/1

**Comment by goulou** [comment]
Hi, 

Unfortunately, the folder's name is already correct... 
And I don't have any error while enabling the app, since I can't enable it :-( 

Frederic. 

----- Mail original -----

De: "lebowski42" notifications@github.com 
À: "lebowski42/owncloudapp-dokuwiki" owncloudapp-dokuwiki@noreply.github.com 
Cc: "goulou" fredericg_99@yahoo.fr 
Envoyé: Lundi 30 Septembre 2013 16:01:38 
Objet: Re: [owncloudapp-dokuwiki] App does not appear in owncloud app manager (#2) 

Hi, 

who is the name of folder. Maybee it's ist somethong like 'owncloudapp-dokuwiki-master'. Please rename it to 'dokuwiki'. Then it will work. Also look here: #1
